name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        shell: bash
        run: |
          yarn
          yarn prepack
          node dist/cli.js https://github.com/yue/build-gn/releases/download/v0.11.1/gn_v0.11.1_mac_x64.zip gn
          ls -l gn

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set package version
        run: |
          npm config set git-tag-version=false
          npm version $VERSION

      - name: Install deps
        run: yarn

      - name: Publish npm package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          ignore-scripts: false

      - name: Prepare to publish non-scoped module
        run: sed -i 's/\@compilets\/unzip-url/unzip-url/g' package.json

      - name: Publish non-scoped npm package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          ignore-scripts: false
